### ISSUE TITLE
"velox" was removed from CRAN

### ISSUE THREAD

**Issue by oliverbothe** [cjcarlson/embarcadero#14]
My initial attempt to install failed because the package velox was removed from CRAN and is only available from the archive.

**Comment by cjcarlson** [comment]
Oh NO! OK. I'll see what I can do about that.

**Comment by cjcarlson** [comment]
OK. Velox can still be installed. On a Mac, it can be a bit challenging - enough that I've written some notes into the Readme.MD about what to do about it. Let me know if those options don't work for you!
