### ISSUE TITLE
Conflicted "select" function between raster and dplyr.

### ISSUE THREAD

**Issue by vmshirey** [cjcarlson/embarcadero#22]
Hi Colin!

Just dropping a quick note about an error when running bart.step in which the "select" function is not properly defined as coming from either the raster or dplyr libraries:

```
library(conflicted)
sdm <- bart.step(y.data=dat[,"occurrence"], x.data=dat[,xnames], full=TRUE, quiet=TRUE)
```

_Error: [conflicted] `select` found in 2 packages.
Either pick the one you want with `::` 
* raster::select
* dplyr::select
Or declare a preference with `conflict_prefer()`
* conflict_prefer("select", "raster")
* conflict_prefer("select", "dplyr")_

**Comment by cjcarlson** [comment]
AH

**Comment by cjcarlson** [comment]
Thank you

**Comment by cjcarlson** [comment]
Should be unconflicted now?
