### ISSUE TITLE
Error from `bart.step()` related to `select()` call

### ISSUE THREAD

**Issue by jbyoder** [cjcarlson/embarcadero#27]
`bart.step()` throws an error 

> unable to find an inherited method for function ‘select’ for signature ‘"data.frame"’

I think this is due to the call to `select()` in the function `varimp.diag()` (line 29 in my copy-paste of the code from the terminal), which doesn't specify the `dplyr` namespace.

**Comment by jbyoder** [comment]
Confirmed that fixing this call to `select()` has got `bart.step()` running as expected.

**Comment by cjcarlson** [comment]
Fixed!
